---
title: "03_Creategermlines_SHM"
author: "Enric Vercher"
date: "2023-11-10"
output: html_document
---

```{r}
# load libraries
suppressPackageStartupMessages(library(airr))
suppressPackageStartupMessages(library(alakazam))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(dowser))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(scoper))
suppressPackageStartupMessages(library(shazam))
suppressPackageStartupMessages(library(tigger))
```


```{r}
All_mice_clustering <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity/All_mice_clusteringt.tsv")

```

```{r}
# From Alakazam
# # run createGermlines using IMGT files in Docker container.
# references <- readIMGT(dir = "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/data_IMGT/germlines/imgt/mouse/vdj")
# 
# All_mice_clustering <- createGermlines(All_mice_clustering,references)
# All_mice_clustering$germline_alignment_d_mask[1]
```


```{r}
m.44.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/mouse_44_final_germlines_germ-pass.tsv")
m.45.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/mouse_45_final_germlines_germ-pass.tsv")
m.48.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/mouse_48_final_germlines_germ-pass.tsv")
m.49.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/mouse_49_final_germlines_germ-pass.tsv")
m.50.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/mouse_50_final_germlines_germ-pass.tsv")
m.52.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/mouse_52_final_germlines_germ-pass.tsv")
```


# Calculate SHM frequency in the V gene

```{r}
# calculate SHM frequency in the V gene
m.44.SHM <- observedMutations(m.44.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)
# Mouse 45
m.45.SHM <- observedMutations(m.45.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)

# Mouse 48
m.48.SHM <- observedMutations(m.48.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)

# Mouse 49
m.49.SHM <- observedMutations(m.49.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)

# Mouse 50
m.50.SHM <- observedMutations(m.50.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)

# Mouse 52
m.52.SHM <- observedMutations(m.52.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)
```

```{r}
all_mice_BCR_final <- rbind(m.44.SHM,m.45.SHM,m.48.SHM,m.49.SHM,m.50.SHM,m.52.SHM)
```

```{r}
write.table(m.44.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/m.44.SHM.tsv", sep = "\t", row.names = FALSE)
write.table(m.45.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/m.45.SHM.tsv", sep = "\t", row.names = FALSE)
write.table(m.48.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/m.48.SHM.tsv", sep = "\t", row.names = FALSE)
write.table(m.49.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/m.49.SHM.tsv", sep = "\t", row.names = FALSE)
write.table(m.50.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/m.50.SHM.tsv", sep = "\t", row.names = FALSE)
write.table(m.52.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/m.52.SHM.tsv", sep = "\t", row.names = FALSE)
```


```{r}
write.table(all_mice_BCR_final, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/all_mice_BCR_final.tsv", sep = "\t", row.names = FALSE)
saveRDS(all_mice_BCR_final, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM_slurm/all_mice_BCR_final.rds")
```

# All the data_together from cloning assigment from the cluster

```{r}
m.all.SHM <- airr::read_rearrangement("C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity_slurm/all_mice_final_germlines_germ-pass.tsv")

```


```{r}
m.all.SHM <- observedMutations(m.all.SHM, 
                            sequenceColumn = "sequence_alignment",
                            germlineColumn = "germline_alignment_d_mask",
                            regionDefinition = IMGT_V_BY_REGIONS,
                            frequency = TRUE,
                            combine = TRUE, 
                            nproc = 1)
```

```{r}
write.table(m.all.SHM, "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM/all_mice_BCR.tsv", sep = "\t", row.names = FALSE)
saveRDS(m.all.SHM,"C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/04_SHM/all_mice_BCR.rds")
```

Luego copiamos all_mice_BCR.tsv como all_mice_BCR_correct.tsv para añadirlo al objeto scRNA Seurat.

# Explote data

```{r}
# calculate the median mutation frequency of a clone
mut_freq_clone <- m.all.SHM %>% 
                  group_by(clone_id) %>% 
                  summarise(median_mut_freq = mean(mu_freq))

ggplot(mut_freq_clone, aes(median_mut_freq)) + 
    geom_histogram(, binwidth = 0.005) + theme_bw() +
    theme(axis.title = element_text(size = 18))
```

```{r}
# calculate the median mutation frequency of a clone
mut_freq_clone <- all_mice_BCR_final %>% 
                  group_by(clone_id) %>% 
                  summarise(median_mut_freq = mean(mu_freq))

ggplot(mut_freq_clone, aes(median_mut_freq)) + 
    geom_histogram(, binwidth = 0.005) + theme_bw() +
    theme(axis.title = element_text(size = 18))
```

```{r}
# calculate the median mutation frequency of a clone
mut_freq_clone <- m.all.SHM %>% 
                  group_by(clone_id) %>% 
                  summarise(median_mut_freq = mean(mu_freq))

ggplot(mut_freq_clone, aes(median_mut_freq)) + 
    geom_histogram(, binwidth = 0.005) + theme_bw() +
    theme(axis.title = element_text(size = 18))
```

# Format clones for tree building in Dowser

```{r}
clones <- formatClones(data_h, 
                       traits = "c_call", columns = "subject", 
                       minseq = 3)
print(clones)
```

# Build trees using maximum likelihood

```{r}
library(phangorn)
trees <- getTrees(clones, build = "pml", nproc = 1)
print(trees)
```

# Build trees using IgPhyML

```{r}
trees <- getTrees(clones, 
                  build = "igphyml", nproc = 1), exec = "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/igphyml/src/ig")
print(trees)
```

```{r}
p <- plotTrees(trees, tips = "c_call", tipsize = 4)
p[[1]]
```

```{r}
# save all trees to a pdf
treesToPDF(p, file = "C:/Users/d940401/Desktop/Analisis_immcantation/Analisis_Enric/Datos_Enric/Datos_TFM/00_Datos_filtrados_slurm/03_Clonal_diversity/alltrees.pdf")
```

```{r}
# update names in alakazam’s default colors (IG_COLORS)
names(IG_COLORS) <- c("IGHA","IGHD","IGHG", "IGHM","IGHG1","IGHG2B","IGHG2C")
# subset data to IgA, IgG and Ig
results_isotype <- subset(data_h, c_call %in% c("IGHD","IGHM","IGHA","IGHG1"))
nrow(results_isotype)
```

# Reconstruct intermediate sequences

```{r}
trees <- collapseNodes(trees)

# plot trees with node ID numbers
p <- plotTrees(trees, tips = "c_call", tipsize = 4, 
               node_nums = TRUE, labelsize = 7)
p[[1]]
```

```{r}
# get the sequence at node 20
first_clone_id <- trees[["clone_id"]][1]
sequence <- getNodeSeq(trees, clone = first_clone_id, node = 20)
print(sequence)
```











